### ISSUE TITLE
"Okay" button does not take me away from site

### ISSUE THREAD

**Issue by unquietpirate** [meitar/timewastercheckin#1]
Expected behavior: Clicking "okay" will take the user to a different site.
What actually happens: Appears to have the same behavior as "Cancel" (just leaves you at the current site.) Might be an issue w my javascript blocker.

**Comment by meitar** [comment]
:\ Actually, the cancel button is the one that's supposed to take you away from the site. The "OK" button is supposed to let you stay for another hour without being nagged.
